[package]
version.workspace = true
description.workspace = true
repository.workspace = true
name = "typort-cli"
edition.workspace = true
license.workspace = true

[[bin]]
name = "typort"
path = "src/main.rs"

[dependencies]
clap.workspace = true
typort-core.workspace = true
typort-ooxml.workspace = true
typort-presets.workspace = true

[dev-dependencies]
zip.workspace = true
typst.workspace = true
typst-pdf.workspace = true
typort-presets.workspace = true
