[package]
version.workspace = true
description.workspace = true
repository.workspace = true
name = "typort-core"
edition.workspace = true
license.workspace = true

[dependencies]
typst.workspace = true
typst-library.workspace = true
typst-syntax.workspace = true
typst-kit.workspace = true
typst-utils.workspace = true
typst-realize.workspace = true
typst-html.workspace = true
typst-render.workspace = true
typst-layout.workspace = true
typort-ooxml.workspace = true
typort-math.workspace = true
typort-presets.workspace = true
resvg.workspace = true
tiny-skia.workspace = true
image.workspace = true
hayagriva.workspace = true
time.workspace = true
ttf-parser.workspace = true
